### ISSUE TITLE
Dimensions do not match

### ISSUE THREAD

**Issue by 4465** [mickeystroller/ETypeClus#2]
![image](https://user-images.githubusercontent.com/30649756/133738750-7231913d-b684-4056-9579-199c3c4ef129.png)
I run this command, it get this error.
how to solve it. thanks!!
![image](https://user-images.githubusercontent.com/30649756/133738892-4104c91c-a222-4c1a-95be-20806e8e6601.png)

**Comment by mickeysjm** [comment]
You can specify the input feature dim [here](https://github.com/jmshen1994/ETypeClus/blob/main/latent_space_clustering.py#L307). The default dim is set to 1000 but you can change it to other values.
